
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 10000
        max-idle: 200
        max-active: -1
        min-idle: 0
    timeout: 10000
    block-when-exhausted: true

